# Generated by Django 4.1 on 2026-02-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSub4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('firstTime', models.TimeField(null=True)),
                ('firstDate', models.DateField(blank=True, null=True)),
                ('firstLocation', models.TextField(blank=True, null=True)),
                ('IndoorTime', models.TimeField(blank=True, null=True)),
                ('IndoorDate', models.DateField(blank=True, null=True)),
                ('IndoorLocation', models.TextField(blank=True, null=True)),
                ('OutdoorTime', models.TimeField(blank=True, null=True)),
                ('OutdoorDate', models.DateField(blank=True, null=True)),
                ('OutdoorLocation', models.TextField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, max_length=100, null=True)),
                ('bestTime', models.TimeField(blank=True, null=True)),
                ('bestDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
