# Generated by Django 4.1 on 2023-08-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletesub4',
            name='pbTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
