# Generated by Django 4.1 on 2026-03-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('is_first_sub4', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='sub4.athlete')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
