# Generated by Django 4.1 on 2023-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0002_alter_athletesub4_pbtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesub4',
            name='bestTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
