# Generated by Django 4.1 on 2023-10-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0003_athletesub4_besttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletesub4',
            name='firstIndoor',
        ),
        migrations.RemoveField(
            model_name='athletesub4',
            name='pbIndoor',
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='IndoorDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='IndoorLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='IndoorTime',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='OutdoorDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='OutdoorLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='OutdoorTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='firstLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesub4',
            name='pbLocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
