# Generated by Django 4.1 on 2023-10-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0004_remove_athletesub4_firstindoor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletesub4',
            name='firstTime',
            field=models.TimeField(null=True),
        ),
    ]
