# Generated by Django 4.1 on 2023-10-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0005_alter_athletesub4_firsttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesub4',
            name='bestDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
