# Generated by Django 3.2.6 on 2023-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletesub4',
            name='countries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athletesub4',
            name='pbTime',
            field=models.TimeField(null=True),
        ),
    ]
